"""ShiftTemplateModel add startDate and endDate

Revision ID: 8b53e60cbf4c
Revises: 
Create Date: 2026-01-18 00:34:12.660517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b53e60cbf4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_templates', sa.Column('startDate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shift_templates', sa.Column('endDate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_templates', 'endDate')
    op.drop_column('shift_templates', 'startDate')
    # ### end Alembic commands ###
