"""add created_at to shift_templates

Revision ID: 9f7ee4def596
Revises: 8b53e60cbf4c
Create Date: 2026-01-18 00:51:51.201213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f7ee4def596'
down_revision: Union[str, None] = '8b53e60cbf4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_templates', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_templates', 'created_at')
    # ### end Alembic commands ###
